GET localhost:8080/accounts
Authorization: Bearer eyJraWQiOiJhMTgxOGEzNy02YjI4LTRlYzYtYWEwMS05ODg3MTBiM2IzMmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImF1ZCI6Im1lc3NhZ2luZy1jbGllbnQiLCJuYmYiOjE3Mjg5NDIxNDIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJtZXNzYWdlLnJlYWQiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzI4OTQyNDQyLCJpYXQiOjE3Mjg5NDIxNDIsImp0aSI6IjQyMDM4MWRjLTVlMGEtNDAzMS1iOTNiLTNlMDYwN2IxMTUwMiJ9.gH39jqBTvpqnn5CiZ19ePC1cMB0tgRqK3EscFHLnIZ_c4RAGl4kCfWdkxgeu1xBmCcRQG0g7gmEia4PydDjO7rn5xPjVtxkmYv9qIuS1cIDo3DorPzDult9CuJxX5OaejH6XkonLqTZTEFzA3ch62amN34opIxrym9mRQUJ4gQ2Brf5APWat4n_pj7J7Rm-q6EP2P9G9XRlwODdpAoP1xiH6jXPuLXSTFjFJxg43Ein7aeA7y-Nku4h67V3PSibvtOTJMBPYPjlcb2x-8FE2WbLPMlNeDKs2NqjphUceKhOgLnZeSjsVJcWTr-OxwtvLFbpMjxS2k0iFLCZXQPwzHw
