server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
spring.security.oauth2:
      client:
        registration:
         user-accounts-app-oidc:
            provider: spring
            client-id: user-accounts-app
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile, accounts.read
            client-name: user-accounts-app-oidc
        provider:
          spring:
            issuer-uri: http://localhost:9000
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:9000/oauth2/jwks
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/user/**

