server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
spring.security.oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            #redirect-uri: "http://127.0.0.1:8080/login/authenticate"
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile,message.read
            client-name: messaging-client-oidc
        provider:
          spring:
            issuer-uri: http://localhost:9000
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:9000/oauth2/jwks
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: account-service
          uri: http://localhost:8083
          predicates:
            - Path=/accounts
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/user/*/accounts

