GET http://localhost:8084/user/1/accounts
Authorization: Bearer eyJraWQiOiI0NWEyNDNhNi05NjNjLTQ4OGItYTE4OC1hN2MyMGEyNDJiNDQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImF1ZCI6Im1lc3NhZ2luZy1jbGllbnQiLCJuYmYiOjE3MjkwMzM5MTUsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJtZXNzYWdlLnJlYWQiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzI5MDM0MjE1LCJpYXQiOjE3MjkwMzM5MTUsImp0aSI6ImFlN2Q1NTI0LTVhMDItNDE5OC05YTdhLTRlOTE1NTk2YTU5NiJ9.PVgEFXEAKJMc2y7KOs-sUibqqTiZA7NZSeNWNdBgcLd4YiXwpKnrUHIHD8IcM_cuBt1-GUjciuRUXbEenWv85qczD3Gcp_fYJvhwYKlMitFJkXG33xOx60IKMQRUnpDGWW1CJEgDxb1WDpkk5j4FX2KChiLiRnL3R8eiXAbuR3FJPaVoQIdvEmfc7XLAmfF9qDbPr_lsHbpX7KkkxRIN6jns6anpKX20IYvV_rVmzT2zfF-jZWO3mq9aDuN8x7FUnYdF8GLl6kKWV0J0vyY614Hu8D6Fi0BhjRSWf5WX5yNeF2-qiB5zK69OTQWc3tGq6s7WDfhwyxBT7gUEHjynZg

###
GET http://localhost:8084/health